### PR TITLE
Fix Bug of Skipping Top Left Corner

### PR DESCRIPTION
**Pull request by Plantchant**
Fixes bug that made the code skip the very top left pixel of the image.

### CODE REVIEW

**Comment by rdeepak2002** [comment]
Feel free to merge these changes since you are now a collaborator

**Comment by robiot** [comment]
> Feel free to merge these changes since you are now a collaborator 

Is it really a good thing making everybody a collaborator? You shouldnt. There should be you and someone else that you trust. Everybody that are collaborators can push straight to the main branch and delete the entire codebase and commit history.

**Comment by rdeepak2002** [comment]
@robiot 

I completely agree with what you said. The reason why I made most people who created meaningful pull request collaborators is because I am a student who is busy studying for upcoming exams and I did not expect this repo that I made in 1 hour as a side project to become popular. Most other people I know are also students, so they also do not have the time to maintain the repo and merge all the feature requests and bug fixes. 

I also felt like this is a low-risk project in the sense that r/place is a 4-day event that allows people to place pixels on a subreddit. Thus, I would find it hard to believe that someone would create a meaningful pull request and spend the time to nuke the entire repository after that. 

But I do agree with what you said and I will not be adding anymore collaborators from this point forwards. 

Thank you.

**Comment by thoroc** [comment]
There should be some reviewers though and no push to main.

**Review by thoroc — APPROVED** [review]

**Comment by Plantchant** [comment]
Added via Commit since Approved and source has changed too much to merge

**Comment by robiot** [comment]
Closing then. But remember to try to not push directly to main. There is always an solution

**Pull request closed without merging**
