### PR TITLE
Updated Black Shield to For The Badge

### PR DESCRIPTION
**Pull request by Skyline-9**

### CODE REVIEW

**Comment by thoroc** [comment]
Please run `nox -rs black`, commit and push again.

**Comment by Skyline-9** [comment]
Man I just changed the README, Nox doesn't even change anything so I have nothing to commit
image

**Comment by thoroc** [comment]
Apologies, there are a lot of white spaces changes and I was hoping it was because black was involved.

**Review by thoroc — APPROVED** [review]

**Comment by Skyline-9** [comment]
Ok wtf my editor showed the badge, I guess GitHub doesn't like the base64?

**Pull request merged**
