### PR TITLE
Replaced rate limit exit from ban to exit thread

### PR DESCRIPTION
**Pull request by Risewill23**

### CODE REVIEW

**Review by ixi2101 — CHANGES_REQUESTED** [review]
Looks like your line endings are all borken

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by Risewill23** [comment]
Does it need to be CRLF or LF

**Comment by ixi2101** [comment]
LF I believe

**Comment by Risewill23** [comment]
Oh I have the file set to CRLF for some reason then

**Review by ixi2101 — APPROVED** [review]

**Pull request merged**
