### PR TITLE
Changes to linter

### PR DESCRIPTION
**Pull request by ixi2101**
Checks for black changes in the linter
No longer applies black before running linter

### CODE REVIEW

**Comment by robiot** [comment]
Shouldnt we have a workflow to check that they follow linting rules on pull request. Not fix it, just check

**Comment by ixi2101** [comment]
We already run nox as a workflow. This changes that workflow to fail if there are format changes to be made

**Review by robiot — APPROVED** [review]
lgtm

**Comment by RomainL972** [comment]
Maybe we should add instructions for contributors for how to format their code properly so they can contribute

**Pull request merged**
