### PR TITLE
Tor fix

### PR DESCRIPTION
**Pull request by Risewill23**
Hanged when launching the tor subprocess

### CODE REVIEW

**Review by rdeepak2002 — APPROVED** [review]

**Comment by LukachoLombardi** [comment]
Could you specify what setup you're using? For me it works without major problems, as the Shell=true statement should open Tor in a new window

**Comment by Risewill23** [comment]
I'm using windows 11 and running the program in vs code's terminal

**Comment by LukachoLombardi** [comment]
I used the same setup except I use pycharm instead. But hey, if it works it works lol

**Comment by LukachoLombardi** [comment]
Also I just read what the difference between run and Popen is and I don't get why it even worked for me this whole time

**Comment by LukachoLombardi** [comment]
You did test this right?

**Comment by Risewill23** [comment]
Not in a correct testing way because all my alts are rate limit banned but tor looks to be working fine because of the rate limit errors are getting sent back

**Comment by LukachoLombardi** [comment]
Ok👍 but I just noticed that the start command should open a new she'll window. So it could be that there's some suppressed error coming from CMD trying to start Tor and blocking the script

**Pull request merged**
