### PR TITLE
Change Update Frequency to match reddits new pixel delay

### PR DESCRIPTION
**Pull request by njalooo**
Reddit changed the cooldown for setting pixels to 20min, so i adjusted the pixel placement frequency, since this might cause reddit to detect them as bots otherwise.

### CODE REVIEW

**Comment by Risewill23** [comment]
It's still 5 minutes for me and not 20

**Comment by TNT599** [comment]
It is only 20 minutes for unverified accounts.

**Comment by ixi2101** [comment]
Perhaps it should be a config option

**Comment by Risewill23** [comment]
It's now a setting now

**Pull request closed without merging**
