### PR TITLE
use defaults for missing config settings instead of throwing exception

### PR DESCRIPTION
**Pull request by CallMeKass**

### CODE REVIEW

**Comment by thoroc** [comment]
Is that line correct?
> if "thread_delay" in self.json_data and ["thread_delay"] is not None

**Comment by rdeepak2002** [comment]
Shouldn't line 36 be:
```python
... self.json["thread_delay"] is not None
```

**Comment by robiot** [comment]
This is a mess to merge :sob:

**Comment by robiot** [comment]
This should work now

**Comment by RomainL972** [comment]
This pull request canceled recent changes. Can you do it again from the current main branch ?

**Comment by robiot** [comment]
Do what again?

**Comment by RomainL972** [comment]
Recreate the pull request. I can do it if necessary

**Comment by robiot** [comment]
> Recreate the pull request. I can do it if necessary

You can do it

**Comment by robiot** [comment]
Hey @RomainL972
You just reverted this whole pull request. Please dont

**Comment by RomainL972** [comment]
Hi,
Sorry about that, I should have handled that differently. The merging of this pull request in the main branch instantly broke the script on my side and I thought it was the easiest way to solve it to revert it and recreate the pull request (I did that in https://github.com/rdeepak2002/reddit-place-script-2022/pull/214).

**Pull request merged**
