### PR TITLE
Improved output in logging

### PR DESCRIPTION
**Pull request by bjb28**
This PR adds the work's name to several relative logs and changes the category of the below logs. By doing these changes it makes it easier to run logging level SUCCESS to see that the script is working. 

The log output with names will be as followed:

`YYYY-MM-DD HH:MM:SS.mmm | SUCCESS  | __main__:set_pixel_and_check_ratelimit:176 WORKNAME: Succeeded placing pixel`

Changed logs:

- Line 116: Loading image goes from info to success
- Line 125: Attempting to place from info to warning
- Line 175: Succeeded placing pixel from info to success
- Line 448: Bad credentials form info to critical

### CODE REVIEW

**Review by thoroc — APPROVED** [review]

**Comment by thoroc** [comment]
Please rebase. The changes looks good. 👍

**Comment by bjb28** [comment]
Took a while to hit a working setup to rebase on but this appears to be working now. Is anyone able to review it?

**Comment by thoroc** [comment]
Apologies, the development was that fast that your changes seems to have drown in the flow.

**Comment by thoroc** [comment]
Might be an idea to create a new branch and cherry pick because right now it is almost impossible to properly review this. :/

**Comment by bjb28** [comment]
@thoroc I was thinking the same thing. But it was a good experience playing with rebasing. I will create a new branch and PR tonight as I think having the username in the log is helpful. I will close this one out and open a new one later on.

**Comment by bjb28** [comment]
Closing to do the changes in a new branch.

**Pull request closed without merging**
