### PR TITLE
Fix threading and canvas/pixel position calculations.

### LINKED ISSUE #133: [BUG] Places pixel at wrong location
My config used 1436, 529, but it was trying to build the image at 436, 529. This is using the latest version (5a424c0)

### PR DESCRIPTION
**Pull request by russianfool**
Should fix #133

### CODE REVIEW

**Review by robiot — APPROVED** [review]
LGTM. Tho I cannot test it right now. Please test it before merging

**Review by Keigun-Spark — APPROVED** [review]
Tested with art. Successfully defended and placed on correct spots.

**Comment by smith558** [comment]
Does not work. With setting `"image_start_coords": [251, 253]`, starts placing tiles at (253, 253) instead

**Comment by smith558** [comment]
@JAKONL @russianfool still buggy

**Comment by Phyronian** [comment]
This worked for me, unsure if it works with multiple accounts however.
Testing in the next few minutes

**Comment by nsk126** [comment]
Still buggy, multiple accounts draw on the same point.



```
Got image: 

Account Placing:  usr1 

[03-Apr-22 04:09:30] :: [INFO] - Attempting to place Dark Red (1) pixel at 1442, 266
[03-Apr-22 04:09:31] :: [INFO] - Succeeded placing pixel 
[03-Apr-22 04:09:32] :: [INFO] - Thread #0 :: 
Got image: 

Account Placing:  usr2 

[03-Apr-22 04:09:32] :: [INFO] - Attempting to place Dark Red (1) pixel at 1442, 266
[03-Apr-22 04:09:33] :: [INFO] - Succeeded placing pixel 

```

**Comment by Keigun-Spark** [comment]
That is a different issue. Before the placement was completely off.

**Comment by nsk126** [comment]
Still buggy, multiple accounts draw on the same point.



```
Got image: 

Account Placing:  usr1 

[03-Apr-22 04:09:30] :: [INFO] - Attempting to place Dark Red (1) pixel at 1442, 266
[03-Apr-22 04:09:31] :: [INFO] - Succeeded placing pixel 
[03-Apr-22 04:09:32] :: [INFO] - Thread #0 :: 
Got image: 

Account Placing:  usr2 

[03-Apr-22 04:09:32] :: [INFO] - Attempting to place Dark Red (1) pixel at 1442, 266
[03-Apr-22 04:09:33] :: [INFO] - Succeeded placing pixel 

```

**Comment by russianfool** [comment]
@smith558 I see an off-by-one error (maybe) when trying to reproduce what you're talking about. 251,253 turns into 252,253 for me at the point where I fixed the calculations. This commit doesn't address it, only the off-by-1000 stuff happening with the canvas. Check that the pixels aren't already the right color, and that your per-worker offset is set correctly.

@nsk126 That's a race condition between the pixel check and placement, not related to the fix or ticket.

**Comment by JAKONL** [comment]
I'm running this code on my maintained area and I am not seeing the incorrect offset mentioned. @smith558 -- is it possible that the threads are skipping those pixels as they are already set to the correct color?

**Comment by smith558** [comment]
> I'm running this code on my maintained area and I am not seeing the incorrect offset mentioned. @smith558 -- is it possible that the threads are skipping those pixels as they are already set to the correct color?

they weren't  set to the right colour

**Comment by nsk126** [comment]
Has anyone found the fix to the race condition issue between pixel check & placement? It seems to happen even when I use single accounts in the config and run multiple processes.

**Pull request merged**
