### PR TITLE
Delete black.yml

### PR DESCRIPTION
**Pull request by robiot**
Does no longer work

### CODE REVIEW

**Comment by robiot** [comment]
This can be temporary.

**Comment by RomainL972** [comment]
Do we know why it's not working anymore ?

**Review by ixi2101 — CHANGES_REQUESTED** [review]
There must be a better way to disable it other than deleting the file

**Comment by robiot** [comment]
It will no longer work. Instead format it locally

**Comment by robiot** [comment]
> Do we know why it's not working anymore ?

Because main is protected

**Comment by robiot** [comment]
> There must be a better way to disable it other than deleting the file

Well having a action to commit as a user is pretty weird. It is just much better if it checks if code styles are good on pull request. If not request changes from author.

**Comment by ixi2101** [comment]
> > There must be a better way to disable it other than deleting the file
> 
> Well having a action to commit as a user is pretty weird. It is just much better if it checks if code styles are good on pull request. If not request changes from author.

We can enable a setting on the linter that will fail if black would make changes. Then we can only merge if the linter is happy

**Review by ixi2101 — APPROVED** [review]

**Comment by robiot** [comment]
> > > There must be a better way to disable it other than deleting the file
> > 
> > 
> > Well having a action to commit as a user is pretty weird. It is just much better if it checks if code styles are good on pull request. If not request changes from author.
> 
> We can enable a setting on the linter that will fail if black would make changes. Then we can only merge if the linter is happy

Yes exactly!

**Review by RomainL972 — APPROVED** [review]

**Pull request merged**
