### PR TITLE
Potential Fix to the New Canvas

### PR DESCRIPTION
**Pull request by PopcornPlant**
Potential Fix to the Y>999 error from the new canvas.

### CODE REVIEW

**Comment by PopcornPlant** [comment]
Someone has to test it. I'm not at a place where I can.

**Comment by PopcornPlant** [comment]
Someone fix the merge too. It's only 3 lines

**Comment by erolm-a** [comment]
That's not enough I'm afraid, it will get the x-coordinate wrong in the set_pixel code. See #317 (mine) or #316 .

**Comment by ixi2101** [comment]
#317 merged

**Pull request closed without merging**
