### PR TITLE
Add option for custom config.json location

### PR DESCRIPTION
**Pull request by ixi2101**
Adds option to point to a config.json
QoL update. Defaults to config.json

eg
`python main -c ../my-config.json`

### CODE REVIEW

**Comment by robiot** [comment]
Is this really needed? If you use a custom json file, there will be a probability that it may get pushed to the repo, which is not what you want to, since it contains all your passwords and so.

**Comment by ixi2101** [comment]
This saves developers from having to copy/paste config.json around to different versions. 
The idea is to store your config.json completely out of the repo

**Review by RomainL972 — APPROVED** [review]
I think it could be useful, for example if you want to put the config in another folder, or if you want to easily change the used config for tests or whatever. In any case it doesn't hurt to support the feature if someone needs it.

**Review by rdeepak2002 — APPROVED** [review]
Lgtm

**Pull request merged**
