### PR TITLE
Disable all other threads while waiting for board to have needed changes

### PR DESCRIPTION
**Pull request by funwithtriangles**
Improves on my previous PR which makes threads wait for 10 seconds if the board doesn't require any changes. This PR makes sure all other threads are inactive during this time, otherwise they end up competing for the same pixel when a change is required.

### CODE REVIEW

**Comment by RomainL972** [comment]
Can you resolve the conflicts ?

**Review by thoroc — APPROVED** [review]

**Comment by funwithtriangles** [comment]
Sorry, went to bed! Doing this now

**Comment by funwithtriangles** [comment]
This should all be good now! There is now a global variable `self.waiting_thread_index`. If `-1`, then all things run as normal. If a thread detects there is nothing wrong with the image, it sets itself as the waiting thread and just keeps checking every 10 seconds if it needs to make a change. Once it detects a change and places a pixel, `waiting_thread_index` goes back to `-1` and all threads become active again.

**Review by RomainL972 — CHANGES_REQUESTED** [review]
Fix conflicts please

**Review by RomainL972 — APPROVED** [review]

**Pull request merged**
