### PR TITLE
Add thread index in logging

### PR DESCRIPTION
**Pull request by RomainL972**
This is usefull to know which thread is concerned when placing a pixel (or failing to do so)

### CODE REVIEW

**Review by Frigyes06 — APPROVED** [review]

**Review by kleith — APPROVED** [review]

**Review by thoroc — CHANGES_REQUESTED** [review]
Looking good but since there is a merge conflict you might need to rebase

**Comment by robiot** [comment]
I'll fix merge conflicts

**Comment by RomainL972** [comment]
Done

**Comment by RomainL972** [comment]
I had to convert main.py from CRLF to LF again

**Comment by robiot** [comment]
Force push :sob:
Merging

**Comment by thoroc** [comment]
You should be able to set that automatically https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Pull request merged**
