### PR TITLE
Added Support for Tor with automatic reconnecting

### PR DESCRIPTION
**Pull request by LukachoLombardi**
basically what the title says. It can be turned on and off and it can be used with an integrated binary or your own tor executable. I had to use httptunnel because I couldn't get socks working and didn't want to waste my time fixing soemthing that seems to workl. If you spot something that I should change, just tell me! Additional information in the readme.

### CODE REVIEW

**Comment by ixi2101** [comment]
Including the Tor binaries in the repo doesn't seem like a good idea.

**Comment by LukachoLombardi** [comment]
I know but it makes using it way easier. Also you can still run your own Tor service for this. The alternative would be to include a guide on how to use the Tor expert package and how to modify torrc for this use case. Imo this all in one approach makes sense for this type of use case, but that's just my opinion so if everyone is against it I'll find another solution

**Comment by ixi2101** [comment]
Could you add the tor functionality to the Dockerfile instead?

**Comment by LukachoLombardi** [comment]
But then it would only work with docker

**Comment by Vilsol** [comment]
But including Win-only binaries limits the feature as well.

**Comment by thoroc** [comment]
Not a fan of adding bin files tied up to a single OS either.

**Comment by LukachoLombardi** [comment]
I know adding binaries is generally frowned upon but the Tor expert package isn't even available on Macos

**Comment by LukachoLombardi** [comment]
But if it's that big of a problem I can just remove the bundled version and provide a guide on how to do it yourself

**Comment by thoroc** [comment]
@rdeepak2002  what's your thoughts on that? you are the repo owner after all. :)

**Comment by rdeepak2002** [comment]
@thoroc

Hey I think this feature looks good. I also think its fine to include the binaries for now as long as we document in the README that it only works on certain OS's, etc.

**Comment by Vilsol** [comment]
Would be great if instructions for other platforms was included in the PR

**Comment by LukachoLombardi** [comment]
so I was working on removing the binaries, but if it's ok to keep them then that's not bad either. @rdeepak2002 could you rerun the nox workflow? It seems like I didn't use nox and black right so it failed the last time.

**Comment by LukachoLombardi** [comment]
> Would be great if instructions for other platforms was included in the PR

I could add instructions for mac os but that would probably contain having to compile tor from scratch

**Comment by Vilsol** [comment]
> > Would be great if instructions for other platforms was included in the PR
> 
> I could add instructions for mac os but that would probably contain having to compile tor from scratch

I was more thinking for Linux, I doubt many run this on mac

**Comment by LukachoLombardi** [comment]
I mainly use windows and I'm not that well versed with docker, so someone else should probably do that

**Comment by LukachoLombardi** [comment]
Also nox works perfectly for me locally. I have no idea why it fails here

**Comment by LukachoLombardi** [comment]
@rdeepak2002 could I get your final verdict wheter or not we should include the binaries? I've included a guide and I could easily remove the binaries, so should I keep them or not?

**Comment by LukachoLombardi** [comment]
also as I said nox isn't working on here

**Comment by ixi2101** [comment]
> also as I said nox isn't working on here

Your noxfile is out of date

**Comment by LukachoLombardi** [comment]
it should work now

**Review by ixi2101 — APPROVED** [review]

**Comment by ixi2101** [comment]
Merging before the influx from new canvas

**Pull request merged**
