### PR TITLE
Dynamic Canvas Size

### PR DESCRIPTION
**Pull request by maltejur**
Does the `# TODO` :D

### CODE REVIEW

**Comment by thoroc** [comment]
this is tested aye?

**Comment by maltejur** [comment]
Yup

**Comment by thoroc** [comment]
Please run black: `nox -rs black` and push again. :)

**Comment by maltejur** [comment]
No idea why the check fails, everything works fine for me locally

image

**Comment by Vilsol** [comment]
This is now even more important since it expanded

**Comment by ixi2101** [comment]
> No idea why the check fails, everything works fine for me locally

I think your noxfile is out of date.

Has anyone tested this with the new new map?

**Comment by maltejur** [comment]
> I think your noxfile is out of date.

It magically started working now, so I guess problem fixed

> Has anyone tested this with the new new map?

I tested the part that the PR changes and at least that works.

**Comment by Vilsol** [comment]
Running these changes right now, seem to work

**Review by ixi2101 — APPROVED** [review]

**Pull request merged**
