### PR TITLE
[Please Don't Merge Anymore pull request until this one] W.I.P Use Json, Object Orientated, Clean up, Fix errors

### PR DESCRIPTION
**Pull request by robiot**
I am currently trying to fix merge conflicts, so not merging other pull requests for a while would be handy.

This is now reading from json instead of .env. But there are some problems ex. KeyError: 'access_token' first time, etc. I will fix them.

When you merge this, I would recommend using Squash and Merge, since that makes the commit tree much more clean.

(Don't merge yet)

### CODE REVIEW

**Comment by thoroc** [comment]
Got a PR in https://github.com/rdeepak2002/reddit-place-script-2022/pull/72. Ping me when you're done with this one. :)

**Comment by robiot** [comment]
For some reason the cooldown is INCREDIBLY high 
image

**Comment by robiot** [comment]
I will merge this now, so other prs can be merged.

**Comment by robiot** [comment]
The nox rules will also need to be fixed. I will fix asap

**Pull request merged**
